print("Let's calculate the compund interest\nProvide following informations:")
name=input("Write your name:")
collage=input("Collage name=")
print(f'HEY!!',name," your collage name is :",collage," \nNow we can start lets go!!")
print('enter principle amount:')
p=int(input('enter value of p='))
print('enter rate:')
r=int(input('enter r='))
print('enter the no. of years the investment is done for = n')
n=int(input('enter the value of n='))
print('compund interest value =',p*(1+(r/100))**n)